In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [4]:
# no need nested for loop
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for x in np.nditer(a,order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
# fortran order (columns)
for x in np.nditer(a,order="F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [7]:
# whole col
for x in np.nditer(a,order="F", flags=["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [8]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...] = x*x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [9]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [12]:
for x, y in np.nditer([a,b]): # automatically stays in b row until a finishes
    print(x,y) # shape must be same or need a 1D (broadcastable)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
